const IMAGEDETAIL = {
    LOAD:'IMAGEDETAIL_LOAD',
    LOADING:'IMAGEDETAIL_LOADING',
    SUCCESS:'IMAGEDETAIL_SUCCESS',
    FAILURE:'IMAGEDETAIL_FAILURE',
    LIKE:'IMAGEDETAIL_LIKE',
    INC:'IMAGEDETAIL_INCREMENT_LIKE'
} 

const COMMENT = {
    LOAD:'COMMENT_LOAD',
    SUBMIT:'COMMENT_SUBMIT',
    DELETE:'COMMENT_DELETE',
    LOADING:'COMMENT_LOADING',
    SUCCESS:'COMMENT_SUCCESS',
    FAILURE:'COMMENT_FAILURE'
} 

const IMAGES = {
    LOAD:'IMAGES_LOAD',
    LOADING:'IMAGES_LOADING',
    SUCCESS:'IMAGES_SUCCESS',
    FAILURE:'IMAGES_FAILURE'
}

const IMAGE = {
    ADD:'IMAGE_ADD'
}

export {IMAGEDETAIL, IMAGES, COMMENT, IMAGE}